---
# tasks file for slurm

- name: Include Slurm controller tasks
  include_tasks: slurm-controller-install.yaml
  when: slurm_playbook_type == 'controller'

- name: Include Slurm DBD tasks
  include_tasks: slurm-dbd-install.yaml
  when: slurm_playbook_type == 'controller'

- name: Include Slurm exec node tasks
  include_tasks: slurm-exec-install.yaml
  when: slurm_playbook_type == 'exec'

- name: Create nfs server
  include_tasks: nfs_server.yaml
  when: nfs_server == 'true'