---
- name: Install NFS server packages
  dnf:
    name: nfs-utils
    state: present
    update_cache: yes

- name: Create the exported directory
  file:
    path: "{{ nfs_export_path }}"
    state: directory
    mode: '0755'

- name: Configure NFS exports
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_export_path }} {{ nfs_allowed_clients }}"
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'

- name: Enable and start NFS server service
  systemd:
    name: nfs-server
    state: started
    enabled: true
